### ISSUE TITLE
[Ferature request] add examples.

### ISSUE THREAD

**Issue by dreirund** [budlabs/genmonify#7]
Ahoj,

thanks for this software.

I did not really work out how this exactly works.

I suggest a feature request for the documentation to add examples:

* One directory `/usr/share/doc/genmonify/examples/` which contains ready-made example configuration,
* in the usage section of the [`README.md`](https://github.com/budlabs/genmonify/blob/next/README.md#options) one example with a concrete module showing step by step what do to.

For me it is not clear what holds as a valid "module" for genmon; `xfce4-genmon-plugin` is a plugin which just shows `stdout` of a command one can specify manually so I can enter any complex command I want in the preferences dialogue of the plugin.

Regards!

**Comment by budRich** [comment]
there is a guide (2 steps) and an example in the readme.

One thing I use this for is to display the window title of the active window. Sure i could do this by just adding a command in genmon which would output the active window title. But the problem is that genmon works on a set interval, and i don't want to check for and print the window title every second, that would be wasteful, and also get weird if the title changes faster than than the interval. Instead I have a script that watches for window title/focus change and when that occurs it triggers `genmonify -o windowtitle "$title"`. 

![2022-06-15-12:06:23](https://user-images.githubusercontent.com/2143465/173802755-65b85af4-6123-4929-bc71-e1ed564a393e.png)
